AllCops:
  NewCops: 'enable'
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - '*.gemspec'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 99

Style/Documentation:
  Enabled: false

Style/MapIntoArray:
  Exclude:
    - 'spec/reading/**/*.rb' # most specs call each intentionally since a Stream is an Enumerable
